### ISSUE TITLE
Server ip address (website url) not working.

### ISSUE THREAD

**Issue by wpolk** [jkelol111/localStorage#1]
When I do:
`localStorage = lc('http://127.0.0.1:224/')`
it raises WinError 123:
`OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\William/.localStorage/http://127.0.0.1:224/'
`
Do you know how I would grt this to wor?

**Comment by sunsetsonwheels** [comment]
Hi, some characters cannot be used with localStoragePy, such as path separators `/ \`.

Edit: I will have to edit the README to mention this, and add checks in the code.

**Comment by sunsetsonwheels** [comment]
I have updated the library. Please reread the README for more information.
